- {ccmHistoryRunningLastChanged: '681990168', ccmHistoryRunningLastSaved: '681839591',
  ccmHistoryStartupLastChanged: '681839591', sysUptime: '682011400'}
- {ccmHistoryRunningLastChanged: '681990168', ccmHistoryRunningLastSaved: '681839591',
  ccmHistoryStartupLastChanged: '681839591', sysUptime: '682071482'}
- {ccmHistoryRunningLastChanged: '682080234', ccmHistoryRunningLastSaved: '681839591',
  ccmHistoryStartupLastChanged: '681839591', sysUptime: '682131562'}
- {ccmHistoryRunningLastChanged: '682260215', ccmHistoryRunningLastSaved: '681839591',
  ccmHistoryStartupLastChanged: '681839591', sysUptime: '682322506'}
- {ccmHistoryRunningLastChanged: '682350184', ccmHistoryRunningLastSaved: '681839591',
  ccmHistoryStartupLastChanged: '681839591', sysUptime: '682412585'}
